### Assemble this Week's Model

In [16]:
import model as md
import over_under as ou
import pandas as pd

### Update The CSV

In [2]:
raw = ou.get_over_under()

In [5]:
raw.to_csv('ou_full.csv')

### Manually Insert Weather

In [13]:
weather = md.get_current_games(7)

In [14]:
weather.to_csv('updated_weather.csv')

**Go into excel and manually update the weather**

In [20]:
check = pd.read_csv('updated_weather.csv', index_col=0)

In [21]:
check.head()

,home_team,away_team,total_line,TPAPG,TPPG,temp,wind,gameday,good_o_good_d,good_o_bad_d,bad_o_good_d,bad_o_bad_d
6798,NO,DEN,37.0,40.500000,46.500000,70,0,2024-10-17,0,0,1,0
6799,JAX,NE,42.0,53.500000,32.666667,70,0,2024-10-20,0,0,0,1
6800,ATL,SEA,51.0,47.500000,49.166667,70,0,2024-10-20,1,0,0,0
6801,BUF,TEN,41.0,43.000000,46.700000,67,14,2024-10-20,0,0,1,0
6802,CLE,CIN,41.5,48.833333,42.000000,69,9,2024-10-20,0,0,0,1

### Get The Predictions

**_Takes a Minute_**

In [22]:
data = md.model_output(7, insert='') #insert the week

In [23]:
data #Check Schedule is Correct

,home_team,away_team,total_line,TPAPG,TPPG,temp,wind,gameday,good_o_good_d,good_o_bad_d,bad_o_good_d,bad_o_bad_d,prediction,pred-actual,prob_correct_pred
6798,NO,DEN,37.0,40.500000,46.500000,70,0,2024-10-17,0,0,1,0,42.5,5.5,1.000
6799,JAX,NE,42.0,53.500000,32.666667,70,0,2024-10-20,0,0,0,1,40.5,-1.5,0.237
6800,ATL,SEA,51.0,47.500000,49.166667,70,0,2024-10-20,1,0,0,0,45.5,-5.5,0.781
6801,BUF,TEN,41.0,43.000000,46.700000,67,14,2024-10-20,0,0,1,0,43.0,2.0,0.892
6802,CLE,CIN,41.5,48.833333,42.000000,69,9,2024-10-20,0,0,0,1,43.0,1.5,0.794
6803,GB,HOU,47.5,42.666667,50.833333,76,14,2024-10-20,1,0,0,0,45.0,-2.5,0.644
6804,IND,MIA,43.5,45.766667,35.166667,70,0,2024-10-20,0,0,1,0,39.5,-4.0,0.287
6805,MIN,DET,50.5,33.400000,58.000000,70,0,2024-10-20,1,0,0,0,45.0,-5.5,0.724
6806,NYG,PHI,42.5,42.566667,37.200000,76,4,2024-10-20,0,0,1,0,40.0,-2.5,0.230
6807,LA,LV,43.5,54.966667,36.966667,70,0,2024-10-20,0,0,0,1,42.5,-1.0,0.287
6808,WAS,CAR,51.5,58.000000,46.833333,74,4,2024-10-20,0,0,0,1,47.5,-4.0,1.000
6809,SF,KC,47.0,38.666667,50.600000,84,2,2024-10-20,1,0,0,0,44.5,-2.5,0.700
6810,PIT,NYJ,38.5,32.333333,39.500000,59,3,2024-10-20,0,0,1,0,37.5,-1.0,0.042
6811,TB,BAL,49.5,48.333333,59.166667,86,13,2024-10-21,0,1,0,0,50.5,1.0,0.242
6812,ARI,LAC,44.0,40.366667,40.366667,70,0,2024-10-21,0,0,1,0,40.0,-4.0,0.344

In [24]:
data.to_csv('week7_output.csv')

**Insert the above file into the R_Photos file and run the 'p' one**